baseurl: "/js-students" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://htc-ccis2591.github.io/" # the base hostname & protocol for your site
title: "CCIS 2591 JavaScript"

exclude:
  - "README.md"
  - "Gemfile"
